const SB_URL='https://xghxnxdlnkdezcuxledv.supabase.co';
const SB_KEY='sb_publishable_5kW2tTUTMJLBNWcmzGSo4w_qz2ZZnoO';
const $=id=>document.getElementById(id);
let session=null,refreshPromise=null;
let questions=[],sharedQuestions=[],quizzes=[],quizLinks=[],tags=[];
const pickedQuestionIds=new Set(),quizQuestionIds=new Set(),editorPickedIds=new Set();
const sortState={questions:{key:'created_at',dir:'desc'},shared:{key:'term',dir:'asc'}};

function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setMessage(id,text,error=false){const el=$(id);el.textContent=text;el.style.color=error?'#b44b57':'#177a89'}
function saveSession(value){session=value;if(value)localStorage.setItem('medlex-session',JSON.stringify(value));else localStorage.removeItem('medlex-session')}
function showLogin(message='登入已逾時，請重新登入。'){saveSession(null);$('appView').classList.add('hidden');$('authView').classList.remove('hidden');setMessage('authMessage',message,true)}
async function refreshSession(){if(!session?.refresh_token)throw new Error('Missing refresh token');if(!refreshPromise)refreshPromise=fetch(SB_URL+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:SB_KEY,Authorization:'Bearer '+SB_KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token})}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.message||data.error_description||'無法更新登入');saveSession(data);return data}).finally(()=>{refreshPromise=null});return refreshPromise}
async function request(path,opt={}){const {retryAuth=true,...fetchOpt}=opt;const token=path.startsWith('/auth/v1/')?SB_KEY:(session?.access_token||SB_KEY);const response=await fetch(SB_URL+path,{...fetchOpt,headers:{apikey:SB_KEY,Authorization:'Bearer '+token,'Content-Type':'application/json',...(fetchOpt.headers||{})}});if(response.status===401&&retryAuth&&session?.refresh_token&&!path.startsWith('/auth/v1/')){try{await refreshSession();return request(path,{...fetchOpt,retryAuth:false})}catch{showLogin();throw new Error('登入已逾時，請重新登入。')}}if(!response.ok){let body={};try{body=await response.json()}catch{}throw new Error(body.message||body.error_description||('Request failed: '+response.status))}if(response.status===204)return null;const text=await response.text();return text?JSON.parse(text):null}

async function auth(mode){try{setMessage('authMessage','處理中…');const path=mode==='signup'?'/auth/v1/signup':'/auth/v1/token?grant_type=password';const data=await request(path,{method:'POST',body:JSON.stringify({email:$('email').value.trim(),password:$('password').value})});if(mode==='signup'&&!data.access_token){setMessage('authMessage','帳號已建立，請先到信箱完成驗證。');return}saveSession(data);await start()}catch(error){setMessage('authMessage',error.message,true)}}
async function start(){if(!session)return;$('authView').classList.add('hidden');$('appView').classList.remove('hidden');$('account').textContent=session.user.email;await loadAll()}
async function loadSharedQuestions(){try{return await request('/rest/v1/shared_questions?select=*&order=term.asc')}catch{return (window.CLINICAL_QUESTIONS||[]).map((q,index)=>({id:'local-'+index,term:q.term,clue:q.clue,category:q.category||'臨床醫學'}))}}
async function loadTags(){const derived=[...new Set(questions.flatMap(tagsOf))];try{let rows=await request('/rest/v1/tags?select=*&order=name.asc');const known=new Set(rows.map(tag=>tag.name)),missing=derived.filter(name=>!known.has(name));if(missing.length){await request('/rest/v1/tags',{method:'POST',headers:{Prefer:'resolution=ignore-duplicates,return=minimal'},body:JSON.stringify(missing.map(name=>({name,owner_id:session.user.id})))});rows=await request('/rest/v1/tags?select=*&order=name.asc')}return rows}catch{return derived.sort().map(name=>({id:'derived:'+name,name}))}}
async function loadAll(){try{[questions,sharedQuestions,quizzes,quizLinks]=await Promise.all([request('/rest/v1/questions?select=*&order=created_at.desc'),loadSharedQuestions(),request('/rest/v1/quizzes?select=*&order=created_at.desc'),request('/rest/v1/quiz_questions?select=quiz_id,question_id')]);tags=await loadTags();const available=new Set(questions.map(q=>q.id));[...pickedQuestionIds].forEach(id=>{if(!available.has(id))pickedQuestionIds.delete(id)});renderAll()}catch(error){if(session)alert(error.message)}}
function renderAll(){renderCategoryOptions();renderQuestions();renderTags();renderSharedQuestions();renderQuizzes();renderQuizEditor()}
function sorted(items,table){const {key,dir}=sortState[table];return [...items].sort((a,b)=>String(a[key]??'').localeCompare(String(b[key]??''),'zh-Hant',{numeric:true,sensitivity:'base'})*(dir==='asc'?1:-1))}
function updateSortButtons(){document.querySelectorAll('.sort').forEach(button=>{const state=sortState[button.dataset.sortTable];const active=state.key===button.dataset.sortKey;button.classList.toggle('active',active);button.dataset.arrow=state.dir==='asc'?'↑':'↓';button.setAttribute('aria-sort',active?(state.dir==='asc'?'ascending':'descending'):'none')})}
function setOptions(id,categories){const select=$(id),current=select.value;select.innerHTML='<option value="">全部標籤</option>'+categories.map(value=>`<option value="${escapeHtml(value)}">${escapeHtml(value)}</option>`).join('');select.value=categories.includes(current)?current:''}
function tagsOf(q){return String(q.category||'').split(/[,，、]/).map(tag=>tag.trim()).filter(Boolean)}
function normalizeTags(value){return [...new Set(String(value).split(/[,，、]/).map(tag=>tag.trim()).filter(Boolean))].join(', ')}
function tagChips(q){const tags=tagsOf(q);return tags.length?tags.map(tag=>`<span class="tag">${escapeHtml(tag)}</span>`).join(''):'<span class="muted small">無標籤</span>'}
function renderCategoryOptions(){const personal=tags.map(tag=>tag.name).sort();setOptions('questionCategory',personal);setOptions('quizBankCategory',personal);setOptions('sharedCategory',[...new Set(sharedQuestions.flatMap(tagsOf))].sort())}
function filterItems(items,search,category){const needle=search.trim().toLowerCase();return items.filter(q=>(!category||tagsOf(q).includes(category))&&(!needle||q.term.toLowerCase().includes(needle)||q.clue.toLowerCase().includes(needle)||tagsOf(q).some(tag=>tag.toLowerCase().includes(needle))))}

function renderQuestions(){const rows=sorted(filterItems(questions,$('questionSearch').value,$('questionCategory').value),'questions');$('questionCount').textContent=questions.length+' 題';$('questionRows').innerHTML=rows.map(q=>{const usage=new Set(quizLinks.filter(link=>link.question_id===q.id).map(link=>link.quiz_id)).size;return `<tr><td><input class="pick" type="checkbox" data-pick-question="${q.id}" ${pickedQuestionIds.has(q.id)?'checked':''}></td><td><b>${escapeHtml(q.term)}</b></td><td>${escapeHtml(q.clue)}</td><td>${tagChips(q)}</td><td><div class="actions"><span class="muted small">使用於 ${usage} 份測驗</span><button data-edit-question="${q.id}">編輯</button><button class="danger" data-delete-question="${q.id}">刪除</button></div></td></tr>`}).join('')||'<tr><td colspan="5" class="muted">沒有符合條件的題目</td></tr>';const visible=rows.map(q=>q.id);$('selectAllQuestions').checked=visible.length>0&&visible.every(id=>pickedQuestionIds.has(id));$('deleteSelectedBtn').disabled=!pickedQuestionIds.size;updateSortButtons()}
function renderQuestionTagPicker(selected=[]){const chosen=new Set(selected);$('questionTagPicker').innerHTML=tags.map(tag=>`<label class="tag-choice"><input type="checkbox" data-question-tag="${escapeHtml(tag.name)}" ${chosen.has(tag.name)?'checked':''}>${escapeHtml(tag.name)}</label>`).join('')||'<span class="muted">尚未建立標籤</span>'}
function openQuestionDialog(id=''){const q=questions.find(item=>item.id===id);$('questionId').value=q?.id||'';$('term').value=q?.term||'';$('clue').value=q?.clue||'';renderQuestionTagPicker(q?tagsOf(q):[]);$('questionFormTitle').textContent=q?'編輯題目':'新增題目';setMessage('questionFormMessage','');$('questionDialog').showModal()}
async function saveQuestion(){try{const id=$('questionId').value,term=$('term').value.trim().toUpperCase().replace(/[^A-Z]/g,''),clue=$('clue').value.trim();if(term.length<2||!clue)throw new Error('請輸入有效的英文答案與題目提示');const selected=[...document.querySelectorAll('[data-question-tag]:checked')].map(input=>input.dataset.questionTag);const body={term,clue,category:selected.join(', ')||null,owner_id:session.user.id};await request('/rest/v1/questions'+(id?'?id=eq.'+id:''),{method:id?'PATCH':'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)});$('questionDialog').close();setMessage('questionMessage','題目已儲存');await loadAll()}catch(error){setMessage('questionFormMessage',error.message,true)}}
async function deleteQuestions(ids){const used=ids.filter(id=>quizLinks.some(link=>link.question_id===id)).length;if(!confirm('確定刪除 '+ids.length+' 題？'+(used?` 其中 ${used} 題正被測驗使用，也會從這些測驗移除。`:'')))return;try{await request('/rest/v1/questions?id=in.('+ids.join(',')+')',{method:'DELETE'});ids.forEach(id=>pickedQuestionIds.delete(id));await loadAll()}catch(error){setMessage('questionMessage',error.message,true)}}

function tagUsage(name){return questions.filter(q=>tagsOf(q).includes(name)).length}
function renderTags(){$('tagCount').textContent=tags.length+' 個標籤';$('tagRows').innerHTML=tags.map(tag=>`<tr><td><span class="tag">${escapeHtml(tag.name)}</span></td><td>${tagUsage(tag.name)} 題</td><td><div class="actions"><button data-rename-tag="${escapeHtml(tag.id)}">重新命名</button><button class="danger" data-delete-tag="${escapeHtml(tag.id)}">刪除</button></div></td></tr>`).join('')||'<tr><td colspan="3" class="muted">尚未建立標籤</td></tr>'}
async function createTag(){const name=$('newTagName').value.trim();if(!name){setMessage('tagMessage','請輸入標籤名稱',true);return}if(tags.some(tag=>tag.name===name)){setMessage('tagMessage','這個標籤已存在',true);return}try{await request('/rest/v1/tags',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({name,owner_id:session.user.id})});$('newTagName').value='';setMessage('tagMessage','標籤已建立');await loadAll()}catch(error){setMessage('tagMessage',error.message.includes('tags')?'請先在 Supabase SQL Editor 執行最新的 supabase-upgrade.sql':error.message,true)}}
async function updateQuestionsForTag(oldName,newName=''){const affected=questions.filter(q=>tagsOf(q).includes(oldName));for(const q of affected){const next=tagsOf(q).map(tag=>tag===oldName?newName:tag).filter(Boolean);await request('/rest/v1/questions?id=eq.'+q.id,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({category:[...new Set(next)].join(', ')||null})})}}
async function renameTag(id){const tag=tags.find(item=>item.id===id);if(!tag)return;const name=prompt('新標籤名稱',tag.name)?.trim();if(!name||name===tag.name)return;if(tags.some(item=>item.name===name)){setMessage('tagMessage','這個標籤已存在',true);return}try{if(!String(id).startsWith('derived:'))await request('/rest/v1/tags?id=eq.'+id,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({name})});else await request('/rest/v1/tags',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({name,owner_id:session.user.id})});await updateQuestionsForTag(tag.name,name);await loadAll();setMessage('tagMessage','標籤已重新命名')}catch(error){setMessage('tagMessage',error.message,true)}}
async function deleteTag(id){const tag=tags.find(item=>item.id===id);if(!tag||!confirm('刪除「'+tag.name+'」？這個標籤會從 '+tagUsage(tag.name)+' 題中移除。'))return;try{await updateQuestionsForTag(tag.name);if(!String(id).startsWith('derived:'))await request('/rest/v1/tags?id=eq.'+id,{method:'DELETE'});await loadAll();setMessage('tagMessage','標籤已刪除')}catch(error){setMessage('tagMessage',error.message,true)}}

function renderSharedQuestions(){const rows=sorted(filterItems(sharedQuestions,$('sharedSearch').value,$('sharedCategory').value),'shared');const owned=new Set(questions.map(q=>q.term));$('sharedCount').textContent=sharedQuestions.length+' 題';$('sharedQuestionRows').innerHTML=rows.map(q=>`<tr><td><b>${escapeHtml(q.term)}</b></td><td>${escapeHtml(q.clue)}</td><td>${tagChips(q)}</td><td>${owned.has(q.term)?'<span class="badge">已加入</span>':`<button data-copy-shared="${escapeHtml(q.term)}">加入我的題庫</button>`}</td></tr>`).join('')||'<tr><td colspan="4" class="muted">沒有符合條件的題目</td></tr>';updateSortButtons()}
async function copySharedQuestion(term){const q=sharedQuestions.find(item=>item.term===term);if(!q)return;try{await request('/rest/v1/questions',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({term:q.term,clue:q.clue,category:q.category||'共同題庫',owner_id:session.user.id})});setMessage('sharedMessage','已加入：'+q.clue+' → '+q.term);await loadAll()}catch(error){setMessage('sharedMessage',error.message,true)}}
async function importClinicalQuestions(){if(!confirm('將尚未擁有的共同題庫題目全部加入嗎？'))return;const existing=new Set(questions.map(q=>q.term)),rows=sharedQuestions.filter(q=>!existing.has(q.term)).map(q=>({term:q.term,clue:q.clue,category:q.category||'共同題庫',owner_id:session.user.id}));if(!rows.length){setMessage('sharedMessage','共同題庫已全部加入');return}try{for(let i=0;i<rows.length;i+=25)await request('/rest/v1/questions',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(rows.slice(i,i+25))});setMessage('sharedMessage','已加入 '+rows.length+' 題');await loadAll()}catch(error){setMessage('sharedMessage',error.message,true)}}

function publicUrl(slug){return new URL('medical-english-crossword.html?quiz='+encodeURIComponent(slug),location.href).href}
function generateQuizSlug(){const random=crypto.getRandomValues(new Uint32Array(1))[0].toString(36);return 'q-'+Date.now().toString(36)+'-'+random}
function quizCount(id){return quizLinks.filter(link=>link.quiz_id===id).length}
function renderQuizzes(){$('quizRows').innerHTML=quizzes.map(q=>`<tr><td><b>${escapeHtml(q.title)}</b><br><small class="muted">${escapeHtml(q.slug)}</small></td><td>${quizCount(q.id)} 題</td><td><span class="badge ${q.is_published?'live':''}">${q.is_published?'已發布':'草稿'}</span></td><td>${q.is_published?`<a href="${publicUrl(q.slug)}" target="_blank">開啟測驗</a> <button data-copy="${escapeHtml(q.slug)}">複製網址</button>`:'—'}</td><td><div class="actions"><button data-edit-quiz="${q.id}">編輯</button><button data-duplicate-quiz="${q.id}">複製測驗</button><button data-publish="${q.id}">${q.is_published?'取消發布':'發布'}</button><button class="danger" data-delete-quiz="${q.id}">刪除</button></div></td></tr>`).join('')||'<tr><td colspan="5" class="muted">尚未建立測驗</td></tr>'}
function showQuizList(){$('quizListView').classList.remove('hidden');$('quizEditorView').classList.add('hidden')}
function showQuizEditor(){$('quizListView').classList.add('hidden');$('quizEditorView').classList.remove('hidden')}
function newQuiz(){$('quizId').value=$('quizTitle').value=$('quizSlug').value='';$('quizFormTitle').textContent='建立測驗';quizQuestionIds.clear();editorPickedIds.clear();setMessage('quizMessage','');renderQuizEditor();showQuizEditor()}
function editQuiz(id){const q=quizzes.find(item=>item.id===id);if(!q)return;$('quizId').value=q.id;$('quizTitle').value=q.title;$('quizSlug').value=q.slug;$('quizFormTitle').textContent='編輯測驗：'+q.title;quizQuestionIds.clear();quizLinks.filter(link=>link.quiz_id===id).forEach(link=>quizQuestionIds.add(link.question_id));editorPickedIds.clear();setMessage('quizMessage','');renderQuizEditor();showQuizEditor()}
function renderQuizEditor(){const available=filterItems(questions.filter(q=>!quizQuestionIds.has(q.id)),$('quizBankSearch').value,$('quizBankCategory').value);$('availableCount').textContent='可選 '+available.length+' 題';$('selectedCount').textContent='已選 '+quizQuestionIds.size+' 題（至少 10 題）';$('addPickedBtn').disabled=!editorPickedIds.size;$('clearQuizQuestions').disabled=!quizQuestionIds.size;$('availableQuestionList').innerHTML=available.map(q=>`<label class="question-item"><input type="checkbox" data-editor-pick="${q.id}" ${editorPickedIds.has(q.id)?'checked':''}><span class="grow"><b>${escapeHtml(q.term)}</b><br><small>${escapeHtml(q.clue)}</small><br>${tagChips(q)}</span></label>`).join('')||'<div class="muted">沒有可加入的題目</div>';$('selectedQuestionList').innerHTML=questions.filter(q=>quizQuestionIds.has(q.id)).map(q=>`<div class="question-item selected-item"><span class="grow"><b>${escapeHtml(q.term)}</b><br><small>${escapeHtml(q.clue)}</small></span><button class="danger" data-remove-from-quiz="${q.id}">移除</button></div>`).join('')||'<div class="muted">尚未加入題目。請從左側題庫挑選。</div>'}
function addPickedToQuiz(){editorPickedIds.forEach(id=>quizQuestionIds.add(id));editorPickedIds.clear();renderQuizEditor()}
async function saveQuiz(){try{const id=$('quizId').value,title=$('quizTitle').value.trim(),slug=id?$('quizSlug').value:generateQuizSlug(),chosen=[...quizQuestionIds];if(!title)throw new Error('請輸入測驗名稱');if(chosen.length<10)throw new Error('每份測驗至少需要 10 題');let quizId=id;if(id){await request('/rest/v1/quizzes?id=eq.'+id,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({title})});await request('/rest/v1/quiz_questions?quiz_id=eq.'+id,{method:'DELETE'})}else{const rows=await request('/rest/v1/quizzes',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({title,slug,owner_id:session.user.id})});quizId=rows[0].id}await request('/rest/v1/quiz_questions',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(chosen.map(question_id=>({quiz_id:quizId,question_id})))});await loadAll();showQuizList();setMessage('quizListMessage','測驗已儲存，分享網址已自動產生')}catch(error){setMessage('quizMessage',error.message,true)}}
async function duplicateQuiz(id){const source=quizzes.find(q=>q.id===id);if(!source)return;try{const rows=await request('/rest/v1/quizzes',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({title:source.title+' 副本',slug:generateQuizSlug(),owner_id:session.user.id})}),links=quizLinks.filter(link=>link.quiz_id===id);if(links.length)await request('/rest/v1/quiz_questions',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(links.map(link=>({quiz_id:rows[0].id,question_id:link.question_id})))});await loadAll();setMessage('quizListMessage','已複製測驗並產生新網址')}catch(error){setMessage('quizListMessage',error.message,true)}}
async function togglePublish(id){const q=quizzes.find(item=>item.id===id);if(!q)return;if(!q.is_published&&quizCount(id)<10){setMessage('quizListMessage','至少 10 題才能發布',true);return}try{await request('/rest/v1/quizzes?id=eq.'+id,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({is_published:!q.is_published})});await loadAll()}catch(error){setMessage('quizListMessage',error.message,true)}}
async function deleteQuiz(id){if(!confirm('確定刪除這份測驗？題庫內的題目不會被刪除。'))return;try{await request('/rest/v1/quizzes?id=eq.'+id,{method:'DELETE'});await loadAll()}catch(error){setMessage('quizListMessage',error.message,true)}}

function showView(view){document.querySelectorAll('.tab').forEach(tab=>tab.classList.toggle('active',tab.dataset.view===view));$('questionsView').classList.toggle('hidden',view!=='questions');$('tagsView').classList.toggle('hidden',view!=='tags');$('sharedView').classList.toggle('hidden',view!=='shared');$('quizzesView').classList.toggle('hidden',view!=='quizzes');if(view==='quizzes')showQuizList()}
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.id==='newQuestionBtn')openQuestionDialog();if(b.id==='saveQuestionBtn')saveQuestion();if(b.id==='cancelQuestionBtn')$('questionDialog').close();if(b.id==='deleteSelectedBtn')deleteQuestions([...pickedQuestionIds]);if(b.id==='createTagBtn')createTag();if(b.id==='importClinicalBtn')importClinicalQuestions();if(b.id==='newQuizBtn')newQuiz();if(b.id==='backToQuizList')showQuizList();if(b.id==='addPickedBtn')addPickedToQuiz();if(b.id==='clearQuizQuestions'){quizQuestionIds.clear();renderQuizEditor()}if(b.id==='saveQuizBtn')saveQuiz();if(b.id==='previewQuizBtn'){const slug=$('quizSlug').value;if(slug)window.open(publicUrl(slug),'_blank');else setMessage('quizMessage','請先儲存測驗，系統才會產生分享網址',true)}if(b.dataset.editQuestion)openQuestionDialog(b.dataset.editQuestion);if(b.dataset.deleteQuestion)deleteQuestions([b.dataset.deleteQuestion]);if(b.dataset.renameTag)renameTag(b.dataset.renameTag);if(b.dataset.deleteTag)deleteTag(b.dataset.deleteTag);if(b.dataset.copyShared)copySharedQuestion(b.dataset.copyShared);if(b.dataset.editQuiz)editQuiz(b.dataset.editQuiz);if(b.dataset.duplicateQuiz)duplicateQuiz(b.dataset.duplicateQuiz);if(b.dataset.publish)togglePublish(b.dataset.publish);if(b.dataset.deleteQuiz)deleteQuiz(b.dataset.deleteQuiz);if(b.dataset.removeFromQuiz){quizQuestionIds.delete(b.dataset.removeFromQuiz);renderQuizEditor()}if(b.dataset.copy)navigator.clipboard.writeText(publicUrl(b.dataset.copy)).then(()=>setMessage('quizListMessage','網址已複製'))})
document.addEventListener('click',event=>{const b=event.target.closest('.sort');if(!b)return;const state=sortState[b.dataset.sortTable];state.dir=state.key===b.dataset.sortKey&&state.dir==='asc'?'desc':'asc';state.key=b.dataset.sortKey;b.dataset.sortTable==='questions'?renderQuestions():renderSharedQuestions()})
document.addEventListener('change',event=>{const input=event.target;if(input.dataset.pickQuestion){input.checked?pickedQuestionIds.add(input.dataset.pickQuestion):pickedQuestionIds.delete(input.dataset.pickQuestion);renderQuestions()}if(input.id==='selectAllQuestions'){filterItems(questions,$('questionSearch').value,$('questionCategory').value).forEach(q=>input.checked?pickedQuestionIds.add(q.id):pickedQuestionIds.delete(q.id));renderQuestions()}if(input.dataset.editorPick){input.checked?editorPickedIds.add(input.dataset.editorPick):editorPickedIds.delete(input.dataset.editorPick);renderQuizEditor()}})
;['questionSearch','questionCategory'].forEach(id=>$(id).addEventListener(id.includes('Search')?'input':'change',renderQuestions));
['sharedSearch','sharedCategory'].forEach(id=>$(id).addEventListener(id.includes('Search')?'input':'change',renderSharedQuestions));
['quizBankSearch','quizBankCategory'].forEach(id=>$(id).addEventListener(id.includes('Search')?'input':'change',renderQuizEditor));
document.querySelectorAll('.tab').forEach(tab=>tab.onclick=()=>showView(tab.dataset.view));
$('loginBtn').onclick=()=>auth('login');$('signupBtn').onclick=()=>auth('signup');$('logoutBtn').onclick=()=>{saveSession(null);location.reload()};
try{session=JSON.parse(localStorage.getItem('medlex-session'))}catch{}if(session)start();
