const SB_URL='https://xghxnxdlnkdezcuxledv.supabase.co';
const SB_KEY='sb_publishable_5kW2tTUTMJLBNWcmzGSo4w_qz2ZZnoO';
let session=null,questions=[],sharedQuestions=[],quizzes=[];
const $=id=>document.getElementById(id);
function setMessage(id,text,error=false){const el=$(id);el.textContent=text;el.style.color=error?'#b44b57':'#177a89'}
function setSharedMessage(text,error=false){setMessage('sharedMessage',text,error);setMessage('questionMessage',text,error)}
async function request(path,opt={}){const token=session?.access_token||SB_KEY;const response=await fetch(SB_URL+path,{...opt,headers:{apikey:SB_KEY,Authorization:'Bearer '+token,'Content-Type':'application/json',...(opt.headers||{})}});if(!response.ok){let body={};try{body=await response.json()}catch{}throw new Error(body.message||body.error_description||('Request failed: '+response.status))}if(response.status===204)return null;const text=await response.text();return text?JSON.parse(text):null}
function saveSession(value){session=value;if(value)localStorage.setItem('medlex-session',JSON.stringify(value));else localStorage.removeItem('medlex-session')}
async function auth(mode){try{setMessage('authMessage','處理中…');const path=mode==='signup'?'/auth/v1/signup':'/auth/v1/token?grant_type=password';const data=await request(path,{method:'POST',body:JSON.stringify({email:$('email').value.trim(),password:$('password').value})});if(mode==='signup'&&!data.access_token){setMessage('authMessage','帳號已建立，請先到信箱完成驗證。');return}saveSession(data);await start()}catch(error){setMessage('authMessage',error.message,true)}}
async function start(){if(!session)return;$('authView').classList.add('hidden');$('appView').classList.remove('hidden');$('account').textContent=session.user.email;await loadAll()}
async function loadSharedQuestions(){try{return await request('/rest/v1/shared_questions?select=*&order=term.asc')}catch{return (window.CLINICAL_QUESTIONS||[]).map((q,index)=>({id:'local-'+index,term:q.term,clue:q.clue}))}}
async function loadAll(){try{[questions,sharedQuestions,quizzes]=await Promise.all([request('/rest/v1/questions?select=*&order=created_at.desc'),loadSharedQuestions(),request('/rest/v1/quizzes?select=*&order=created_at.desc')]);renderQuestions();renderSharedQuestions();renderQuestionChecks();renderQuizzes()}catch(error){alert(error.message)}}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderQuestions(){$('questionCount').textContent=questions.length+' 題';$('questionRows').innerHTML=questions.map(q=>`<tr><td><b>${escapeHtml(q.term)}</b></td><td>${escapeHtml(q.clue)}</td><td>${escapeHtml(q.category||'—')}</td><td><button data-edit-question="${q.id}">編輯</button> <button class="danger" data-delete-question="${q.id}">刪除</button></td></tr>`).join('')||'<tr><td colspan="4" class="muted">尚未建立題目</td></tr>'}
function renderSharedQuestions(){$('sharedCount').textContent=sharedQuestions.length+' 題';const owned=new Set(questions.map(q=>q.term));$('sharedQuestionRows').innerHTML=sharedQuestions.map(q=>`<tr><td><b>${escapeHtml(q.term)}</b></td><td>${escapeHtml(q.clue)}</td><td>${owned.has(q.term)?'<span class="muted">已在我的題庫</span>':`<button data-copy-shared="${escapeHtml(q.term)}">加入我的題庫</button>`}</td></tr>`).join('')||'<tr><td colspan="3" class="muted">共同題庫尚未建立</td></tr>'}
function renderQuestionChecks(){ $('questionChecks').innerHTML=questions.map(q=>`<label class="check"><input type="checkbox" value="${q.id}"><span><b>${escapeHtml(q.term)}</b><br><small>${escapeHtml(q.clue)}</small></span></label>`).join('')||'<span class="muted">請先建立題目</span>'}
async function saveQuestion(){try{const id=$('questionId').value;const term=$('term').value.trim().toUpperCase().replace(/[^A-Z]/g,'');const clue=$('clue').value.trim();if(term.length<2||!clue)throw new Error('請輸入有效的英文答案與提示');const body={term,clue,category:$('category').value.trim()||null,owner_id:session.user.id};await request('/rest/v1/questions'+(id?'?id=eq.'+id:''),{method:id?'PATCH':'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)});resetQuestionForm();setMessage('questionMessage','題目已儲存');await loadAll()}catch(error){setMessage('questionMessage',error.message,true)}}
function editQuestion(id){const q=questions.find(item=>item.id===id);$('questionId').value=q.id;$('term').value=q.term;$('clue').value=q.clue;$('category').value=q.category||'';$('questionFormTitle').textContent='編輯題目';$('cancelQuestionBtn').classList.remove('hidden');scrollTo({top:0,behavior:'smooth'})}
function resetQuestionForm(){$('questionId').value=$('term').value=$('clue').value=$('category').value='';$('questionFormTitle').textContent='新增題目';$('cancelQuestionBtn').classList.add('hidden')}
async function deleteQuestion(id){if(!confirm('確定刪除這題？'))return;try{await request('/rest/v1/questions?id=eq.'+id,{method:'DELETE'});await loadAll()}catch(error){alert(error.message)}}
async function importClinicalQuestions(){
  if(!confirm('要將 100 題臨床醫學英文加入你的題庫嗎？已存在的單字會略過。'))return;
  const existing=new Set(questions.map(q=>q.term));
  const source=sharedQuestions.length?sharedQuestions:window.CLINICAL_QUESTIONS;
  const rows=source.filter(q=>!existing.has(q.term)).map(({term,clue})=>({term,clue,category:'共同題庫',owner_id:session.user.id}));
  if(!rows.length){setSharedMessage('100 題臨床題庫已全部匯入');return}
  try{
    $('importClinicalBtn').disabled=true;
    for(let i=0;i<rows.length;i+=25)await request('/rest/v1/questions',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(rows.slice(i,i+25))});
    setSharedMessage('已匯入 '+rows.length+' 題臨床醫學英文');await loadAll();
  }catch(error){setSharedMessage(error.message,true)}finally{$('importClinicalBtn').disabled=false}
}
async function copySharedQuestion(term){const q=sharedQuestions.find(item=>item.term===term);if(!q)return;try{await request('/rest/v1/questions',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({term:q.term,clue:q.clue,category:'共同題庫',owner_id:session.user.id})});setSharedMessage('已加入：'+q.clue+' → '+q.term);await loadAll()}catch(error){setSharedMessage(error.message,true)}}
function publicUrl(slug){return new URL('medical-english-crossword.html?quiz='+encodeURIComponent(slug),location.href).href}
function renderQuizzes(){$('quizRows').innerHTML=quizzes.map(q=>`<tr><td><b>${escapeHtml(q.title)}</b><br><small>${escapeHtml(q.slug)}</small></td><td><span class="badge ${q.is_published?'live':''}">${q.is_published?'已發布':'草稿'}</span></td><td>${q.is_published?`<a href="${publicUrl(q.slug)}" target="_blank">開啟測驗</a> <button data-copy="${escapeHtml(q.slug)}">複製</button>`:'—'}</td><td><button data-edit-quiz="${q.id}">編輯</button> <button data-publish="${q.id}">${q.is_published?'取消發布':'發布'}</button> <button class="danger" data-delete-quiz="${q.id}">刪除</button></td></tr>`).join('')||'<tr><td colspan="4" class="muted">尚未建立測驗</td></tr>'}
async function saveQuiz(){try{const id=$('quizId').value,title=$('quizTitle').value.trim(),slug=$('quizSlug').value.trim().toLowerCase().replace(/[^a-z0-9-]/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'');const chosen=[...document.querySelectorAll('#questionChecks input:checked')].map(x=>x.value);if(!title||slug.length<3)throw new Error('請輸入測驗名稱與至少 3 字元的網址代碼');if(chosen.length<10)throw new Error('每份測驗至少需要 10 題');let quizId=id;if(id){await request('/rest/v1/quizzes?id=eq.'+id,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({title,slug})});await request('/rest/v1/quiz_questions?quiz_id=eq.'+id,{method:'DELETE'})}else{const rows=await request('/rest/v1/quizzes',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({title,slug,owner_id:session.user.id})});quizId=rows[0].id}await request('/rest/v1/quiz_questions',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(chosen.map(question_id=>({quiz_id:quizId,question_id})))});resetQuizForm();setMessage('quizMessage','測驗已儲存');await loadAll()}catch(error){setMessage('quizMessage',error.message,true)}}
async function editQuiz(id){const q=quizzes.find(item=>item.id===id);$('quizId').value=q.id;$('quizTitle').value=q.title;$('quizSlug').value=q.slug;$('quizFormTitle').textContent='編輯測驗';$('cancelQuizBtn').classList.remove('hidden');document.querySelectorAll('#questionChecks input').forEach(x=>x.checked=false);try{const links=await request('/rest/v1/quiz_questions?select=question_id&quiz_id=eq.'+id);links.forEach(link=>{const input=document.querySelector('#questionChecks input[value="'+link.question_id+'"]');if(input)input.checked=true})}catch(error){alert(error.message)}}
function resetQuizForm(){$('quizId').value=$('quizTitle').value=$('quizSlug').value='';$('quizFormTitle').textContent='建立測驗';$('cancelQuizBtn').classList.add('hidden');document.querySelectorAll('#questionChecks input').forEach(x=>x.checked=false)}
async function togglePublish(id){const q=quizzes.find(item=>item.id===id);try{await request('/rest/v1/quizzes?id=eq.'+id,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({is_published:!q.is_published})});await loadAll()}catch(error){alert(error.message)}}
async function deleteQuiz(id){if(!confirm('確定刪除這份測驗？'))return;try{await request('/rest/v1/quizzes?id=eq.'+id,{method:'DELETE'});await loadAll()}catch(error){alert(error.message)}}
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.dataset.editQuestion)editQuestion(b.dataset.editQuestion);if(b.dataset.deleteQuestion)deleteQuestion(b.dataset.deleteQuestion);if(b.dataset.copyShared)copySharedQuestion(b.dataset.copyShared);if(b.dataset.editQuiz)editQuiz(b.dataset.editQuiz);if(b.dataset.publish)togglePublish(b.dataset.publish);if(b.dataset.deleteQuiz)deleteQuiz(b.dataset.deleteQuiz);if(b.dataset.copy)navigator.clipboard.writeText(publicUrl(b.dataset.copy)).then(()=>alert('網址已複製'))});
document.querySelectorAll('.tab').forEach(tab=>tab.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===tab));$('questionsView').classList.toggle('hidden',tab.dataset.view!=='questions');$('sharedView').classList.toggle('hidden',tab.dataset.view!=='shared');$('quizzesView').classList.toggle('hidden',tab.dataset.view!=='quizzes')});
$('loginBtn').onclick=()=>auth('login');$('signupBtn').onclick=()=>auth('signup');$('logoutBtn').onclick=()=>{saveSession(null);location.reload()};$('saveQuestionBtn').onclick=saveQuestion;$('cancelQuestionBtn').onclick=resetQuestionForm;$('saveQuizBtn').onclick=saveQuiz;$('cancelQuizBtn').onclick=resetQuizForm;
$('importClinicalBtn').onclick=importClinicalQuestions;
try{session=JSON.parse(localStorage.getItem('medlex-session'))}catch{}if(session)start();
